-- =========================================================================
-- booty/config/defaults.lua - Default configuration values
-- =========================================================================
-- DO NOT EDIT THIS FILE - Your changes will be lost on updates!
-- Instead, create/edit: booty/config.lua
-- Only override the values you want to change.
-- =========================================================================

return {
    -- =====================================================================
    -- General Settings
    -- =====================================================================
    general = {
        -- Print debug messages to chat
        debug = false,

        -- Version info (do not change)
        version = "0.2.0",
    },

    -- =====================================================================
    -- Corpse Detection
    -- =====================================================================
    corpse = {
        -- Default horizontal search radius (units)
        default_radius = 30,

        -- Default vertical search radius (units)
        default_zradius = 10,

        -- Maximum allowed radius (prevents accidents)
        max_radius = 200,
    },

    -- =====================================================================
    -- Looting Settings
    -- =====================================================================
    loot = {
        -- Maximum distance to loot a corpse (EQ limit is ~15, we use safety margin)
        max_distance = 15,

        -- Time to wait for loot window to open (ms)
        window_open_timeout = 2000,

        -- Delay between looting individual items (ms)
        item_loot_delay = 50,

        -- Time to wait for item to transfer to inventory (ms)
        item_transfer_timeout = 1000,

        -- Time to wait for corpse to close after looting (ms)
        corpse_close_timeout = 2000,

        -- Skip items with LORE flag if already owned
        skip_owned_lore = true,

        -- Skip NO DROP items by default
        skip_nodrop = true,

        -- Default filter to use (nil = loot everything allowed)
        default_filter = nil,
    },

    -- =====================================================================
    -- Selling Settings
    -- =====================================================================
    sell = {
        -- Delay after selecting an item (ms)
        select_delay = 200,

        -- Time to wait for sell button to respond (ms)
        sell_timeout = 200,

        -- Time to wait for item to leave inventory (ms)
        item_vanish_timeout = 1000,

        -- Bags to never sell from (by index, 1-10)
        protected_bags = {},

        -- Minimum item value to sell (copper) - items below this are destroyed
        -- Set to 0 to sell everything
        min_sell_value = 0,

        -- Never sell items matching these patterns
        never_sell = {
            "Cloudy Potion",
            "Distillate",
        },
    },

    -- =====================================================================
    -- Buff Manager Settings
    -- =====================================================================
    buff = {
        -- Time to wait for spell to memorize (ms)
        memorize_timeout = 15000,

        -- Time to wait for spell to be ready (ms)
        ready_timeout = 20000,

        -- Time to wait for casting to start (ms)
        cast_start_timeout = 1000,

        -- Maximum time to wait for cast to complete (ms)
        cast_complete_timeout = 15000,

        -- Time to wait for target selection (ms)
        target_timeout = 500,

        -- Delay between buff checks (ms)
        check_interval = 1000,

        -- Re-buff when duration falls below this (seconds)
        rebuff_threshold = 60,
    },

    -- =====================================================================
    -- HUD Settings
    -- =====================================================================
    hud = {
        -- Master enable/disable for all HUD elements
        enabled = true,

        -- Ticker/Radar settings
        ticker = {
            enabled = true,
            width = 500,
            y_position = 40,
            fov = 120,          -- Field of view in degrees
            height = 30,

            -- Which spawn types to show
            show_npcs = true,
            show_players = true,
            show_corpses = true,
            show_group = true,

            -- Pin to side of screen ("left", "right", "center", or nil for manual)
            pin = "center",
        },

        -- Player status bar settings
        player_frame = {
            enabled = true,
            x = 100,
            y = 100,
            width = 200,
            height = 20,
            show_hp = true,
            show_mana = true,
            show_endurance = true,
        },

        -- FPS counter settings
        fps = {
            enabled = true,
            history_size = 120,     -- Number of samples to average
            update_interval = 100,  -- Update frequency (ms)
        },
    },

    -- =====================================================================
    -- Filter Settings
    -- =====================================================================
    filter = {
        -- Directory to store filter files (relative to booty/)
        directory = "filters",

        -- Default filter file extension
        extension = ".txt",
    },

    -- =====================================================================
    -- Keybinds (for future use)
    -- =====================================================================
    keybinds = {
        toggle_hud = nil,       -- e.g., "ctrl+h"
        loot_nearest = nil,     -- e.g., "ctrl+l"
        sell_all = nil,         -- e.g., "ctrl+s"
    },
}
